# ##########################################################
# FlatCAM 9 Neo S2
# PDF Source Advisor
# ##########################################################


def _pretty_source(source):
    source = (source or 'unknown').strip().lower()
    mapping = {
        'illustrator': 'Adobe Illustrator',
        'adobe illustrator': 'Adobe Illustrator',
        'coreldraw': 'CorelDRAW',
        'corel': 'CorelDRAW',
        'proteus': 'Proteus',
        'inkscape': 'Inkscape',
        'unknown': 'Unknown'
    }
    return mapping.get(source, source.title())


def _pretty_content(content_type):
    content_type = (content_type or 'unknown').strip().lower()
    mapping = {
        'vector': 'Vector PDF',
        'raster': 'Raster PDF',
        'mixed': 'Mixed vector/raster PDF',
        'unknown': 'Unknown PDF content'
    }
    return mapping.get(content_type, content_type.title())


def advise_pdf_source(analysis):
    """
    Convert PDFContentAnalyzer data into user-facing import guidance.

    This module is informational only. It does not read, parse, import or
    modify PDF geometry.
    """

    analysis = analysis or {}
    source_key = (analysis.get('source') or 'unknown').strip().lower()
    content_key = (analysis.get('content_type') or 'unknown').strip().lower()
    pages = analysis.get('pages') or 0

    source = _pretty_source(source_key)
    content = _pretty_content(content_key)

    rating = 'Experimental'
    recommended_import = 'PDF as Geometry Object'
    advice = []

    if source_key == 'illustrator':
        if content_key == 'vector':
            rating = '5/5'
            recommended_import = 'PDF as Geometry Object'
            advice += [
                'This PDF was generated by Adobe Illustrator.',
                'Vector content was detected.',
                'For PCB manufacturing, exporting only the circuit artwork is recommended.',
                'If SVG is available, SVG Tiny 1.2 may preserve additional semantic information.'
            ]
        elif content_key == 'raster':
            rating = '3/5'
            recommended_import = 'Raster Pipeline'
            advice += [
                'This Illustrator PDF appears to contain raster artwork.',
                'Use the Raster Pipeline only for clean software-generated black and white artwork.',
                'Prefer vector PDF or SVG Tiny 1.2 when possible.'
            ]
        else:
            rating = '3/5'
            advice += [
                'This PDF appears to come from Adobe Illustrator.',
                'Review the detected content type before importing.'
            ]
    elif source_key in ['coreldraw', 'corel']:
        if content_key == 'mixed':
            rating = '4/5'
            recommended_import = 'PDF as Geometry Object'
            advice += [
                'This PDF appears to come from CorelDRAW and contains mixed vector/raster content.',
                'Select only the page containing the PCB.',
                'Remove decorative pages, title blocks and unused artwork before importing.'
            ]
        elif content_key == 'vector':
            rating = '4/5'
            recommended_import = 'PDF as Geometry Object'
            advice += [
                'This PDF appears to come from CorelDRAW.',
                'Vector content was detected.',
                'Export only the PCB page and avoid decorative artwork when possible.'
            ]
        else:
            rating = '3/5'
            advice += [
                'This PDF appears to come from CorelDRAW.',
                'Verify the selected page and simplify the file before importing if needed.'
            ]
    elif source_key == 'proteus':
        if content_key == 'vector':
            rating = '5/5'
            recommended_import = 'PDF as Geometry Object or PDF as Gerber Object'
            advice += [
                'This PDF appears to come from Proteus and contains vector content.',
                'PDF as Geometry Object can be used for geometry extraction.',
                'PDF as Gerber Object may also be suitable when Gerber-style output is desired.'
            ]
        elif content_key == 'raster':
            rating = '3/5'
            recommended_import = 'Raster Pipeline'
            advice += [
                'This PDF appears to contain raster artwork from Proteus.',
                'The Raster Pipeline will convert it through PyMuPDF, Pillow, Potrace, SVG Tiny 1.2 and Geometry.',
                'Use clean high-contrast raster output for best results.'
            ]
        else:
            rating = '3/5'
            advice += [
                'This PDF appears to come from Proteus.',
                'Verify whether the file is vector or raster before machining.'
            ]
    else:
        rating = 'Experimental'
        recommended_import = 'PDF as Geometry Object'
        advice += [
            'Unable to determine the source application.',
            'Verify the PDF before importing.',
            'For CAM work, prefer a clean vector PDF, SVG Tiny 1.2 or Gerber when available.'
        ]

    if pages and pages > 1:
        advice.append('Multiple pages detected. Select only the page containing the PCB.')

    return {
        'source': source,
        'content': content,
        'recommended_import': recommended_import,
        'rating': rating,
        'advice': advice,
        'message': format_pdf_source_advice(source, content, recommended_import, rating, advice)
    }


def format_pdf_source_advice(source, content, recommended_import, rating, advice):
    lines = [
        'PDF Source Advisor:',
        'Source: %s' % source,
        'Content: %s' % content,
        'Recommended Import: %s (%s)' % (recommended_import, rating),
        'Advice:'
    ]
    for item in advice:
        lines.append('- %s' % item)
    return ' '.join(lines)
